services:
  trading-bot:
    build:
      context: .
    stdin_open: true
    tty: true
    container_name: trading-bot
    restart: always
    ports:
      - "8000:8000"
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
    volumes:
      - ./trading-bot:/home/trading-bot
      - ./requirements.txt:/home/requirements.txt
