services:
  trading-bot:
    build:
      context: .
    stdin_open: true
    tty: true
    container_name: trading-bot
    restart: always
    ports:
      - "8050:8050"
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      - BINANCE_ASSET=${BINANCE_ASSET}
      - BINANCE_SYMBOL=${BINANCE_SYMBOL}
    volumes:
      - ./trading-bot:/home/trading-bot
      - ./requirements.txt:/home/requirements.txt
